version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  test-frontend:
    executor:
      name: node/default
    steps:
      - checkout
      - run: cd frontend && npm i && npm run test

  test-backend:
    executor:
      name: node/default
    steps:
      - checkout
      - run: cd backend && npm i && npm run test
    

  build-frontend:
    executor:
      name: node/default
    steps:
      - checkout
      - run: cd frontend && npm i && npm run build
    

  build-backend:
    executor:
      name: node/default
    steps:
      - checkout
      - run: cd backend && npm i && npm run build

workflows:
    build-and-test:
      jobs:
        - test-frontend
        - test-backend:
            requires:
              - test-frontend
        - analyze-backend:
            requires:
              - test-backend
        - analyze-frontend:
            requires:
              - analyze-backend
        - build-backend:
            requires:
              - analyze-frontend
        - build-frontend:
            requires:
              - build-backend
        